carousel/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('seacreatures', views.sea_creatures, name="seacreatures"),
    path('fish', views.fish, name="fish"),
    path('bugs', views.bugs, name="bugs"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carousel/models.py
from django.db import models
from datetime import datetime, time, date, timedelta
from critterticker.settings import BASE_DIR


# Create your models here.


class Month(models.Model):
    # <object.month> returns integer
    MONTH_CHOICES = [
        (1, "January"),
        (2, "February"),
        (3, "March"),
        (4, "April"),
        (5, "May"),
        (6, "June"),
        (7, "July"),
        (8, "August"),
        (9, "September"),
        (10, "October"),
        (11, "November"),
        (12, "December")
    ]
    month_num = models.IntegerField(choices=MONTH_CHOICES)

    def get_abb(self):
        return str(self)[0]

    def __str__(self):
        return self.get_month_num_display()

    def get_int(self):
        return self.month_num


class DiveFish(models.Model):
    SHADOW_MOVEMENT_CHOICES = [
        ('ST', 'stationary'),
        ('SL-', 'very slow'),
        ('SL', 'slow'),
        ('M', 'medium'),
        ('F', 'fast'),
        ('F+', 'very fast')
    ]

    SIZE_CHOICES = [
        ('XS', 'tiny'),
        ('S', 'small'),
        ('M', 'medium'),
        ('L', 'large'),
        ('LT', 'long & thin'),
        ('XL', 'very large'),
        ('XLF', 'very large with fin'),
        ('XXL', 'huge')
    ]

    # id always like "df1", "df20", "df31"...
    id = models.CharField(primary_key=True, max_length=5, default='')
    name = models.CharField(max_length=50, unique=True)
    price = models.IntegerField(default=0)
    movement = models.CharField(max_length=15, choices=SHADOW_MOVEMENT_CHOICES)
    catches_req = models.IntegerField('df catches required', default=0)
    month = models.ManyToManyField(Month, blank=True)
    size = models.CharField(max_length=20, default='XS', choices=SIZE_CHOICES)

    # time interval for daily availability
    interval_start = models.TimeField(default=time.min)
    interval_end = models.TimeField(default=time.max)

    # time interval for df with two available time spans
    interval2_start = models.TimeField(default=time.min)
    interval2_end = models.TimeField(default=time.min)

    def get_hours_display(self):
        start = self.interval_start
        end = self.interval_end
        start2 = self.interval2_start
        end2 = self.interval2_end
        # check if first interval includes whole day (time(0)>time(23,59,59))
        if start == time(0) and end == time(23, 59, 59):
            return "All day"
        # check if no second interval has been provided
        elif start2 == time(0) and end2 == time(0):
            start_formatted = start.strftime('%I').strip('0') + ' ' + start.strftime('%p')
            end_formatted = end.strftime('%I').strip('0') + ' ' + end.strftime('%p')
            return f"{start_formatted} to {end_formatted}"
        else:  # means: there is a second time interval for availability
            display_string = ''
            start_formatted = start.strftime('%I').strip('0') + ' ' + start.strftime('%p')
            end_formatted = end.strftime('%I').strip('0') + ' ' + end.strftime('%p')
            start2_formatted = start2.strftime('%I').strip('0') + ' ' + start2.strftime('%p')
            end2_formatted = end2.strftime('%I').strip('0') + ' ' + end2.strftime('%p')
            display_string += f"{start_formatted} to {end_formatted}"
            display_string += f" /\n{start2_formatted} to {end2_formatted}"
            return display_string

    def __str__(self):
        return self.name

    def get_month_int_list(self):
        int_list = []
        for month in self.month.all():
            int_list.append(month.get_int())
        return int_list

    def month_check(self):
        current_month = date.today().month
        return current_month in self.get_month_int_list()

    # can definitely be simplified!!
    def time_check(self):
        now = datetime.now()
        time_now = time(now.hour, now.minute, now.second)
        start = self.interval_start
        end = self.interval_end
        start2 = self.interval2_start
        end2 = self.interval2_end
        if start2 == end2 == time(0):
            if start < end:
                return start <= time_now <= end
            elif start > end:
                return start <= time_now or time_now <= end
            else:
                raise ValueError('interval_start and interval_end can\'t be the same!')
        else:
            if start < end or start2 < end2:
                return start <= time_now <= end or start2 <= time_now <= end2
            if start > end or start2 > end2:
                return (start <= time_now or time_now <= end) or (start2 <= time_now or time_now <= end2)

    # checks for critters available in under 12 hours (all with datetime objects)
    def time_check_soon(self):
        # checking if critter is available now (with f time_check)
        if self.time_check():
            return False

        now = datetime.now()
        # exchange 'hours' value for other intervals that are meant to signify "soon"
        now_in_12h = now + timedelta(hours=12)
        # checking if month in 12 hours is still in bug_month.all()
        if not now_in_12h.month in self.get_month_int_list():
            return False

        # converting time objects TimeFields to datetime objects
        start_dt = now_in_12h.replace(hour=self.interval_start.hour, minute=0, second=0)
        end_dt = now_in_12h.replace(hour=self.interval_end.hour, minute=self.interval_end.minute,
                                    second=self.interval_end.second)
        start2_dt = now_in_12h.replace(hour=self.interval2_start.hour, minute=0, second=0)
        end2_dt = now_in_12h.replace(hour=self.interval2_end.hour, minute=self.interval2_end.minute,
                                     second=self.interval2_end.second)
        # using same logic as in f time_check:
        if start2_dt == end2_dt == now_in_12h.replace(hour=0, minute=0, second=0):
            if start_dt < end_dt:
                return start_dt <= now_in_12h <= end_dt
            elif start_dt > end_dt:
                return start_dt <= now_in_12h or now_in_12h <= end_dt
        else:
            if start_dt < end_dt or start2_dt < end2_dt:
                return start_dt <= now_in_12h <= end_dt or start2_dt <= now_in_12h <= end2_dt
            if start_dt > end_dt or start2_dt > end2_dt:
                return (start_dt <= now_in_12h or now_in_12h <= end_dt) or \
                       (start2_dt <= now_in_12h or now_in_12h <= end2_dt)

    class Meta:
        verbose_name_plural = "DiveFish"
        ordering = ['name']

    def get_active_number(self):
        num = 0
        for critter in DiveFish.objects.all():
            if critter.month_check() and critter.time_check():
                num += 1
        return num

    def get_not_active_number(self):
        num = 0
        for critter in DiveFish.objects.all():
            if critter.month_check() and not critter.time_check() and not critter.time_check_soon():
                num += 1
        return num

    def get_soon_active_number(self):
        num = 0
        for critter in DiveFish.objects.all():
            if critter.month_check() and critter.time_check_soon():
                num += 1
        return num


class Bug(models.Model):
    LOCATION_CHOICES = [
        ('DISGBEACH', 'disguised on shorelines'),
        ('DISGTREE', 'disguised under trees'),
        ('FLY', 'flying'),
        ('FLYBPBFLOWER', 'flying near blue, purple & black flowers'),
        ('FLYFLOWER', 'flying near flowers'),
        ('LIGHT', 'flying near light sources'),
        ('TRASHTURNIP', 'flying near trash & rotten turnips'),
        ('NEARWATER', 'flying near water'),
        ('HITROCK', 'falls from rocks being hit'),
        ('BEACHROCK', 'on beach rocks'),
        ('FLOWER', 'on flowers'),
        ('PALM', 'on palm trees'),
        ('RIVERPOND', 'on rivers & ponds'),
        ('ROCKBUSH', 'on rocks & bushes'),
        ('TURNIPCANDYLOLLI', 'on rotten turnips, candy & lollipops'),
        ('GROUND', 'on ground'),
        ('STUMP', 'on tree stumps'),
        ('TREE', 'on trees'),
        ('TREEHC', 'on hardwood & cedar trees'),
        ('VILL', 'on villagers'),
        ('WFLOWER', 'on white flowers'),
        ('SNOW', 'pushing snowballs'),
        ('SHAKE', 'falls from shaking trees'),
        ('SHAKEHC', 'shaking hardwood & cedar trees'),
        ('UNDER', 'underground')
    ]

    WEATHER_CHOICES = [
        ("A", "any weather"),
        ("R", "rain only"),
        ("A-R", "any weather except rain")
    ]

    # id always like "b1", "b20", "b31"...
    id = models.CharField(primary_key=True, max_length=5, default='')
    name = models.CharField(max_length=50, unique=True)
    price = models.IntegerField(default=0)
    catches_req = models.IntegerField('b catches required', default=0)
    month = models.ManyToManyField(Month, blank=True)
    location = models.CharField(max_length=40, default='', choices=LOCATION_CHOICES, blank=True)
    weather = models.CharField(max_length=20, choices=WEATHER_CHOICES, default='A')

    # time interval for daily availability
    interval_start = models.TimeField(default=time.min)
    interval_end = models.TimeField(default=time.max)

    # time interval for bf with two available time spans
    interval2_start = models.TimeField(default=time.min)
    interval2_end = models.TimeField(default=time.min)

    def get_hours_display(self):
        start = self.interval_start
        end = self.interval_end
        start2 = self.interval2_start
        end2 = self.interval2_end
        # check if first interval includes whole day (time(0)>time(23,59,59))
        if start == time(0) and end == time(23, 59, 59):
            return "All day"
        # check if no second interval has been provided
        elif start2 == time(0) and end2 == time(0):
            start_formatted = start.strftime('%I').strip('0') + ' ' + start.strftime('%p')
            end_formatted = end.strftime('%I').strip('0') + ' ' + end.strftime('%p')

carousel/views.py
from django.shortcuts import render

from .models import *

# Create your views here.


def home(request):
    return render(request, 'carousel/home.html')


def sea_creatures(request):
    month_list = Month.objects.order_by("month_num")
    dive_fish_list = DiveFish.objects.order_by("name")
    dfactive_number = DiveFish.objects.first().get_active_number()
    dfnot_active_number = DiveFish.objects.first().get_not_active_number()
    dfsoon_active_number = DiveFish.objects.first().get_soon_active_number()
    context = {
        'month_list': month_list,
        'dive_fish_list': dive_fish_list,
        'dfactive_number': dfactive_number,
        'dfnot_active_number': dfnot_active_number,
        'dfsoon_active_number': dfsoon_active_number
    }
    return render(request, 'carousel/sea_creatures.html', context)


def bugs(request):
    month_list = Month.objects.order_by("month_num")
    bug_list = Bug.objects.order_by("name")
    bactive_number = Bug.objects.first().get_active_number()
    bnot_active_number = Bug.objects.first().get_not_active_number()
    bsoon_active_number = Bug.objects.first().get_soon_active_number()
    context = {
        'month_list': month_list,
        'bug_list': bug_list,
        'bactive_number': bactive_number,
        'bnot_active_number': bnot_active_number,
        'bsoon_active_number': bsoon_active_number

    }
    return render(request, 'carousel/bugs.html', context)


def fish(request):
    month_list = Month.objects.order_by("month_num")
    fish_list = Fish.objects.order_by("name")
    factive_number = Fish.objects.first().get_active_number()
    fnot_active_number = Fish.objects.first().get_not_active_number()
    fsoon_active_number = Fish.objects.first().get_soon_active_number()
    context = {
        'month_list': month_list,
        'fish_list': fish_list,
        'factive_number': factive_number,
        'fnot_active_number': fnot_active_number,
        'fsoon_active_number': fsoon_active_number
    }
    return render(request, 'carousel/fish.html', context)

carousel/templates/carousel/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Critter Ticker</title>
    <link rel="stylesheet" href="{% static 'carousel/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'carousel/css/style.css' %}?{%  now 'U' %}">
    {%  block head %}
    {%  endblock %}
</head>
<body>
        {% block content %}
        {%  endblock %}
    <footer id="disclaimer">
        <p>This web project uses game sprites whose copyright is most likely held by the company that developed the<br>
            game. This disclaimer emphasises that the limited number of sprite frames here are used solely for<br>
            informational purposes in the form of a private web development project under the name<br>
            "New Horizons Critter Ticker" - without commercial interest.<br>
            Credit for the images and information goes to
            <a href="https://docs.google.com/spreadsheets/d/13d_LAJPlxMa_DubPTuirkIV4DERBMXbrWQsmSh8ReK4/
            edit#gid=1022368750">this spreadsheet</a>.</p>
        <nav>
            <ul class="navbar">
                <li>
                    <a href="https://nookipedia.com/wiki/Gyroid/New_Horizons"><img src="{% static 'carousel/other images/Gyroid_NH_Inv_Icon.png' %}"
                                        alt="icon for Gyroids"></a>
                </li>
                <li>
                    <a href="https://nookipedia.com/wiki/Art/New_Horizons"><img src="{% static 'carousel/other images/Twinkling_Painting_NH_Icon.png' %}"
                                        alt="icon for Art"></a>
                </li>
                <li>
                    <a href="https://nookipedia.com/wiki/Fossil/New_Horizons"><img src="{% static 'carousel/other images/Fossil_NH_Icon.png' %}"
                                                alt="icon for Fossils"></a>
                </li>
            </ul>
        </nav>
    </footer>
    <script src="{% static 'carousel/js/jquery.min.js' %}"></script>
    <script src="{% static 'carousel/js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $(".owl-carousel").owlCarousel({
                center: true,
                loop: false,
                nav: true,
                margin: 10,
                responsiveClass:true,
                responsive:{
                    0:{
                        items:1,
                    },
                    600:{
                        items:2,
                    },
                    1000:{
                        items:3,
                    }
                }

            })
        })
    </script>
</body>
</html>

{#        $(document).ready(function(){#}
{#            $(".owl-carousel").owlCarousel();#}
{#        });#}

carousel/templates/carousel/bugs.html
{% extends "carousel/base.html" %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
    <div class="help">
        <img class="help-icon" src="{% static 'carousel/other images/question-mark-round-line-icon.png' %}"
         alt="question mark icon for help">
        <p class="help-text">
        Swipe right and left to see non-active,<br> active and soon active critters!
        </p>
    </div>
    <header>
        <h1 class="title">New Horizons Critter Ticker</h1>
        <nav>
            <ul class="navbar">
{#                    <li>#}
{#                        <a href="home">Home</a>#}
{#                    </li>#}
                <li class="current">
                    <a href="bugs"><img src="{% static 'carousel/critter icons/b1.png' %}"
                                        alt="icon for common butterfly"></a>
                </li>
                <li>
                    <a href="fish"><img src="{% static 'carousel/critter icons/f57.png' %}"
                                        alt="icon for horse mackerel"></a>
                </li>
                <li>
                    <a href="seacreatures"><img src="{% static 'carousel/critter icons/df19.png' %}"
                                                alt="icon for chambered nautilus"></a>
                </li>
            </ul>
        </nav>

    </header>

    <main class="owl-carousel">
        {% if bnot_active_number %}
        <section class="column" id="not-active">
            {% for critter in bug_list %}
                {% if critter.month_check and not critter.time_check and not critter.time_check_soon %}
                    <article class="critter-entry">
                        <div class="top">
                            <img src="{% static 'carousel/critter icons/' %}{{ critter.id }}.png" alt='icon for {{ critter.name }}'>

                            <article class="entry-header">
                                <h2>
                                {% for entry in month_list %}
                                    {% if entry.get_int in critter.get_month_int_list %}
                                        <span class="active-month">{{ entry.get_abb }}</span>
                                    {% else %}
                                        <span class="inactive-month">{{ entry.get_abb }}</span>
                                    {% endif %}
                                {% endfor %}
                                </h2>
                                <h1>{{ critter.name|title }} - Not Active</h1>
                            </article>
                        </div>

                        <article class="entry-details">
                            <div class="hours">
                                <img src="{% static 'carousel/other images/clock-timing-icon.png' %}" alt="icon for analog clock">
                                <p>{{ critter.get_hours_display }}</p>
                            </div>

                            <div class="weather">
                                {% if critter.weather == "A" %}
                                    <div class="any">
                                        <img src="{%  static 'carousel/other images/day-sunny-icon.png' %}"
                                             alt="icon for sunny weather">
                                        <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}"
                                             alt="icon for rainy weather">
                                    </div>
                                {% elif critter.weather == "R" %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}" alt="icon for rainy weather">
                                {% else %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon-crossed-out.png' %}" alt="icon for rainy weather crossed out">
                                {% endif %}
                            </div>
                            <div class="location">
                                <img src="{% static 'carousel/other images/map-search-icon.png' %}" alt="icon for map search">
                                <p>{{ critter.get_location_display }}</p>
                            </div>


                            <div class="price">
                                <img src="{% static 'carousel/other images/bells_icon.png' %}" alt="icon for bells currency">
                                <p>{{ critter.price }}</p>
                            </div>

    {#                checking if catches_req should be visible#}
                            <div class="required-catches">
                            {% if critter.catches_req > 0 %}
                                <img src="{% static 'carousel/other images/fishing-net-icon.png' %}" alt="icon for fishing net">
                                <p>after {{ critter.catches_req }} catches</p>
                            {% endif %}
                            </div>

                        </article>
                    </article>
                {% endif %}
            {% endfor %}
        </section>
        {% endif %}
        {% if bactive_number %}
        <section class="column" id="active">
            {% for critter in bug_list %}
                {% if critter.month_check and critter.time_check %}
                    <article class="critter-entry">
                        <div class="top">
                            <img src="{% static 'carousel/critter icons/' %}{{ critter.id }}.png" alt='icon for {{ critter.name }}'>

                            <article class="entry-header">
                                <h2>
                                {% for entry in month_list %}
                                    {% if entry.get_int in critter.get_month_int_list %}
                                        <span class="active-month">{{ entry.get_abb }}</span>
                                    {% else %}
                                        <span class="inactive-month">{{ entry.get_abb }}</span>
                                    {% endif %}
                                {% endfor %}
                                </h2>
                                <h1>{{ critter.name|title }} - Active</h1>
                            </article>
                        </div>

                        <article class="entry-details">
                            <div class="hours">
                                <img src="{% static 'carousel/other images/clock-timing-icon.png' %}" alt="icon for analog clock">
                                <p>{{ critter.get_hours_display }}</p>
                            </div>

                            <div class="weather">
                                {% if critter.weather == "A" %}
                                    <div class="any">
                                        <img src="{%  static 'carousel/other images/day-sunny-icon.png' %}"
                                             alt="icon for sunny weather">
                                        <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}"
                                             alt="icon for rainy weather">
                                    </div>
                                {% elif critter.weather == "R" %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}" alt="icon for rainy weather">
                                {% else %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon-crossed-out.png' %}" alt="icon for rainy weather crossed out">
                                {% endif %}
                            </div>
                            <div class="location">
                                <img src="{% static 'carousel/other images/map-search-icon.png' %}" alt="icon for map search">
                                <p>{{ critter.get_location_display }}</p>
                            </div>


                            <div class="price">
                                <img src="{% static 'carousel/other images/bells_icon.png' %}" alt="icon for bells currency">
                                <p>{{ critter.price }}</p>
                            </div>

    {#                checking if catches_req should be visible#}
                            <div class="required-catches">
                            {% if critter.catches_req > 0 %}
                                <img src="{% static 'carousel/other images/fishing-net-icon.png' %}" alt="icon for fishing net">
                                <p>after {{ critter.catches_req }} catches</p>
                            {% endif %}
                            </div>

                        </article>
                    </article>
                {% endif %}
            {% endfor %}
        </section>
        {% endif %}
        {% if bsoon_active_number %}
        <section class="column" id="soon-active">
            {% for critter in bug_list %}
                {% if critter.month_check and critter.time_check_soon %}
                    <article class="critter-entry">
                        <div class="top">
                            <img src="{% static 'carousel/critter icons/' %}{{ critter.id }}.png" alt='icon for {{ critter.name }}'>

                            <article class="entry-header">
                                <h2>
                                {% for entry in month_list %}
                                    {% if entry.get_int in critter.get_month_int_list %}
                                        <span class="active-month">{{ entry.get_abb }}</span>
                                    {% else %}
                                        <span class="inactive-month">{{ entry.get_abb }}</span>
                                    {% endif %}
                                {% endfor %}
                                </h2>
                                <h1>{{ critter.name|title }} - Soon Active</h1>
                            </article>
                        </div>

                        <article class="entry-details">
                            <div class="hours">
                                <img src="{% static 'carousel/other images/clock-timing-icon.png' %}" alt="icon for analog clock">
                                <p>{{ critter.get_hours_display }}</p>
                            </div>

                            <div class="weather">
                                {% if critter.weather == "A" %}
                                    <div class="any">
                                        <img src="{%  static 'carousel/other images/day-sunny-icon.png' %}"
                                             alt="icon for sunny weather">
                                        <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}"
                                             alt="icon for rainy weather">
                                    </div>
                                {% elif critter.weather == "R" %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon.png' %}" alt="icon for rainy weather">
                                {% else %}
                                    <img src="{% static 'carousel/other images/cloud-rain-icon-crossed-out.png' %}" alt="icon for rainy weather crossed out">
                                {% endif %}
                            </div>
                            <div class="location">
                                <img src="{% static 'carousel/other images/map-search-icon.png' %}" alt="icon for map search">
                                <p>{{ critter.get_location_display }}</p>
                            </div>


                            <div class="price">
                                <img src="{% static 'carousel/other images/bells_icon.png' %}" alt="icon for bells currency">
                                <p>{{ critter.price }}</p>
                            </div>

    {#                checking if catches_req should be visible#}
                            <div class="required-catches">
                            {% if critter.catches_req > 0 %}
                                <img src="{% static 'carousel/other images/fishing-net-icon.png' %}" alt="icon for fishing net">
                                <p>after {{ critter.catches_req }} catches</p>
                            {% endif %}
                            </div>

                        </article>
                    </article>
                {% endif %}
            {% endfor %}
        </section>
        {% endif %}
    </main>

{% endblock %}

carousel/templates/carousel/home.html
{% extends "carousel/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'carousel/css/style.css' %}?{%  now 'U' %}">
{% endblock %}

{% block content %}
<div class="home">
        <h1 class="title">New Horizons Critter Ticker</h1>
        <nav>
            <ul class="navbar">
{#                    <li>#}
{#                        <a href="home">Home</a>#}
{#                    </li>#}
                <li>
                    <a href="bugs"><img src="{% static 'carousel/critter icons/b1.png' %}"
                                        alt="icon for common butterfly"></a>
                </li>
                <li>
                    <a href="fish"><img src="{% static 'carousel/critter icons/f57.png' %}"
                                        alt="icon for horse mackerel"></a>
                </li>
                <li>
                    <a href="seacreatures"><img src="{% static 'carousel/critter icons/df19.png' %}"
                                                alt="icon for chambered nautilus"></a>
                </li>
            </ul>
            <ul class="navbar extra">
                <li>

                </li>
                <li>

                </li>
                <li>

                </li>
            </ul>
        </nav>
    </div>
    <main></main>
{% endblock %}